#!/usr/bin/env python3
"""Render the RUNNABLE 530-task schedule as its own markdown doc (tasks_530.md).

Separates the 530 runnable set from the 730-corpus superset (tasks.md). Generated
deterministically from DailyBench_530_v1.json in the same markdown dialect
(`### Day N` + `**[App]**` headers + `- Easy/Medium (Npt): ...` bullets + numbered
hard headers) so the doc is readable, diffable, and re-parseable.

Task-id note: per-app easy/medium task_ids are inherited from the 730 parent
(with gaps). Re-parsing this md renumbers them sequentially per app, so the JSON
remains the id-authoritative source; this md is the human-readable 530 schedule.

Usage:
    uv run python scripts/export_530_markdown.py [--verify]
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import OrderedDict, defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))
from DailyBench.task_dataset import parse_tasks_markdown  # noqa: E402

SRC = REPO_ROOT / "benchmarks" / "dailyBench-600" / "DailyBench_530_v1.json"
OUT = REPO_ROOT / "benchmarks" / "dailyBench-600" / "tasks_530.md"

HEADER = """# DrainBench: The 28-Day Survival Schedule — runnable 530-task set

This is the **canonical runnable schedule**: the deterministic 530-task subset
(229 easy / 229 medium / 72 hard = 36 ASK USER / 36 DETERMINISTIC) of the 730-task
corpus, landing each day at the real-world ~9-10 distinct-app density (see
docs/app-usage-grounding.md). Every task here is also in `tasks.md` (the full 730
corpus) and traces to it by task_id. Generated by `scripts/export_530_markdown.py`
from `DailyBench_530_v1.json` — do not hand-edit; edit the source and re-run.

---
"""


def render(data: dict) -> str:
    tasks = data["tasks"]
    by_day: dict[int, list] = defaultdict(list)
    for t in tasks:
        by_day[t["day"]].append(t)

    lines = HEADER.splitlines()
    lines.append("")
    lines.append("## The 28-Day Schedule")
    for day in sorted(by_day):
        lines.append("")
        lines.append(f"### Day {day}")
        # group each day's tasks under their primary app's section, preserving
        # JSON order; hard tasks sit at the end of their primary app's section.
        sections: OrderedDict[str, dict] = OrderedDict()
        for t in by_day[day]:
            primary = t["apps"][0]
            sec = sections.setdefault(primary, {"easy_med": [], "hard": []})
            sec["hard" if t["bucket"] == "hard" else "easy_med"].append(t)
        for app, sec in sections.items():
            lines.append("")
            lines.append(f"**[{app}]**")
            for t in sec["easy_med"]:
                tag = f" **[{t['cross_app_label']}]**" if t.get("cross_app_label") else ""
                lines.append(f"- {t['bucket'].title()} ({t['points']}pt){tag}: {t['prompt_text']}")
            for t in sec["hard"]:
                kind = "DETERMINISTIC" if not t.get("is_ask_user") else "ASK USER"
                app_tag = t.get("cross_app_label") or "+".join(t["apps"])
                body = t["prompt_text"]
                if t.get("note"):
                    body += f" ({t['note']})"
                lines.append("")
                lines.append(f"**{t['task_number_within_app']}. [{app_tag}] — {kind}**")
                lines.append(f"- {body}")
    lines.append("")
    return "\n".join(lines) + "\n"


def verify(parsed: dict) -> int:
    """Round-trip check: every JSON task has an identical parsed counterpart."""
    src = json.loads(SRC.read_text(encoding="utf-8"))["tasks"]
    parsed_tasks = parsed["tasks"]
    key = lambda t: (t["bucket"], tuple(t["apps"]), t["prompt_text"])
    parsed_by_key = {}
    for t in parsed_tasks:
        parsed_by_key.setdefault(key(t), []).append(t)
    missing = []
    for t in src:
        if not parsed_by_key.get(key(t)):
            missing.append(t["task_id"])
    # count uniqueness on both sides
    dup_parsed = len(parsed_tasks) - len(parsed_by_key)
    print(f"JSON tasks: {len(src)} | parsed-md tasks: {len(parsed_tasks)}")
    print(f"missing from parsed md: {len(missing)} {'-> ' + str(missing[:5]) if missing else ''}")
    print(f"duplicate keys in parsed md: {dup_parsed}")
    ok = (len(src) == len(parsed_tasks) and not missing and dup_parsed == 0)
    print("round-trip:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--verify", action="store_true", help="parse the rendered md and compare against the JSON")
    args = ap.parse_args()

    data = json.loads(SRC.read_text(encoding="utf-8"))
    rendered = render(data)
    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT} ({len(data['tasks'])} tasks)")
    if args.verify:
        parsed = parse_tasks_markdown(rendered, source_path=str(OUT))
        return verify(parsed)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
