#!/usr/bin/env python3
"""Generate per-day vars files (benchmarks/dailyBench-600/tasks_vars/day_N.env)
directly from the dataset + config + the all-days tasks_vars.local.env reference.

For each requested day this computes the EXACT set of [placeholders] its tasks use
(from the dataset), then emits tasks_vars/day_N.env with a value for each
(priority: tasks_vars.local.env, then config/user.yaml) and a comment naming every
task that uses it. Any placeholder with no value anywhere is listed as OPEN in a
comment and reported, so nothing is silently missed.

Deterministic, idempotent, and it fails loudly (non-zero exit) if a requested day's
placeholder is missing under --strict (Day-1 has none missing).

Usage:
    uv run python scripts/generate_day_vars.py --day 1
    uv run python scripts/generate_day_vars.py --all
    uv run python scripts/generate_day_vars.py --day 1 --strict
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import OrderedDict, defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))
from DailyBench.user_config import load_user_config, parse_flat_config  # noqa: E402

DATASET = REPO_ROOT / "benchmarks" / "dailyBench-600" / "DailyBench_530_v1.json"
CONFIG_PATH = REPO_ROOT / "config" / "user.yaml"
VARS_LOCAL = REPO_ROOT / "benchmarks" / "dailyBench-600" / "tasks_vars.local.env"
VARS_DIR = REPO_ROOT / "benchmarks" / "dailyBench-600" / "tasks_vars"

HEADER = """# Day-{day} vars (runnable 530 subset, {n} tasks).
#
# Auto-generated by scripts/generate_day_vars.py from {dataset} +
# config/user.yaml + tasks_vars.local.env - do NOT hand-edit; re-run to regenerate.
# Pass to the batch runner with:  --vars-file benchmarks/dailyBench-600/tasks_vars/day_{day}.env
# Precedence (low -> high): config/user.yaml  <  this file  <  --var flags.
#
# A placeholder listed as OPEN has no configured value (task uses real/device state);
# add it to config/user.yaml or tasks_vars.local.env if you want to pin it.
"""


def load_dataset(path: Path) -> list[dict]:
    data = json.loads(path.read_text(encoding="utf-8"))
    return data["tasks"] if isinstance(data, dict) else data


def day_placeholders(tasks: list[dict], day: int) -> "OrderedDict[str, list[str]]":
    """placeholder -> task_ids, in first-use order within the day."""
    out: "OrderedDict[str, list[str]]" = OrderedDict()
    for t in tasks:
        if t.get("day") != day:
            continue
        for ph in t.get("placeholders") or []:
            out.setdefault(ph, []).append(t["task_id"])
    return out


def render_day(day: int, tasks: list[dict], values: dict[str, str]) -> tuple[str, list[str]]:
    phs = day_placeholders(tasks, day)
    n = sum(1 for t in tasks if t.get("day") == day)
    lines = HEADER.format(day=day, n=n, dataset=Path(DATASET).name).splitlines()
    lines.append("")
    open_ph: list[str] = []
    for ph in sorted(phs):
        used_by = ", ".join(phs[ph])
        val = values.get(ph)
        if val is None:
            open_ph.append(ph)
            lines.append(f"# [{ph}] used by: {used_by} - OPEN (no configured value)")
        else:
            lines.append(f"# [{ph}] used by: {used_by}")
            lines.append(f"{ph}={val}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n", open_ph


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--day", type=int)
    ap.add_argument("--all", action="store_true", help="generate every day's file")
    ap.add_argument("--strict", action="store_true", help="exit non-zero if any placeholder is OPEN")
    ap.add_argument("--dataset", default=str(DATASET))
    args = ap.parse_args()
    if args.day is None and not args.all:
        raise SystemExit("Pass --day N or --all")

    tasks = load_dataset(Path(args.dataset))
    days = sorted({t["day"] for t in tasks}) if args.all else [args.day]

    cfg = load_user_config(CONFIG_PATH)
    vars_local = parse_flat_config(VARS_LOCAL.read_text(encoding="utf-8")) if VARS_LOCAL.exists() else {}
    values = {**cfg, **vars_local}  # tasks_vars.local.env wins over config

    VARS_DIR.mkdir(parents=True, exist_ok=True)
    exit_code = 0
    for day in days:
        if day is None:
            continue
        content, open_ph = render_day(day, tasks, values)
        out = VARS_DIR / f"day_{day}.env"
        out.write_text(content, encoding="utf-8")
        covered = len([p for p in day_placeholders(tasks, day) if p in values])
        total = len(day_placeholders(tasks, day))
        print(f"wrote {out}  ({covered}/{total} placeholders pinned"
              + (f", OPEN: {', '.join(open_ph)}" if open_ph else "") + ")")
        if open_ph and args.strict:
            print(f"  STRICT: day {day} has OPEN placeholders: {', '.join(sorted(open_ph))}")
            exit_code = 1
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
